# docker-compose.yml

version: "3.9"

services:
  db:
    image: postgres:15.1-alpine
    container_name: postgres-digitalms
    restart: on-failure
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      PGUSER: "${POSTGRES_USER}"
#    ports:
#     - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 1s
      retries: 3

  bot:
      container_name: bot-digitalms
      build:
        context: .
        dockerfile: Dockerfile
      restart: on-failure
      env_file:
        - .env
      environment:
        POSTGRES_HOST: db
      links:
        - db
      depends_on:
        - db
      entrypoint: ["python", "-m", "src.main"]

networks:
  lan_digitalms:
    name: lan_digitalms
    external: true
    driver: bridge
